#  https://github.com/hellxz/SpringCloudLearn
spring:
  application:
    name: config-server  # 应用名称
  cloud:
    config:
      #config服务端参数
      server:
        #        health:
        #          repositories:
        #            myservice:
        #              label: mylabel
        #            myservice-dev:
        #              name: myservice
        #              profiles: development
        git:
          uri: https://github.com/yqlArvin/config-server #配置文件所在仓库
          username: yqlArvin #登录账号
          password: yql15083870385 #登录密码
          default-label: master #配置文件分支
          search-paths: src/main/resources/server-config-files  #配置文件所在根目录

server:
  port: 3301

